# Generated by Django 4.1.5 on 2023-02-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalrecord', '0002_alter_patientinformation_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not to say', 'Rather not to say')], default='', max_length=100, null=True),
        ),
    ]
